blank_issues_enabled: false
contact_links:
  - name: 📖 Documentation
    url: https://elasticbridge.dev
    about: Read the official documentation
  - name: 💬 Community Discussions
    url: https://github.com/Lacasera/elastic-bridge/discussions
    about: Join the community discussions for general questions and ideas
  - name: 🔒 Report a Security Vulnerability (Private)
    url: https://github.com/Lacasera/elastic-bridge/security/advisories/new
    about: Privately report serious security vulnerabilities
